Repository bancolombia/scaffold-clean-architecture, pull requests merged in 2020-06, with the labels that each got.

#59 Change of cobertura plugin for jacoco plugin
  README.md
  gradle.properties
  src/main/java/co/com/bancolombia/templates/PluginTemplate.java
  src/main/java/co/com/bancolombia/templates/ScaffoldTemplate.java
  src/main/java/co/com/bancolombia/templates/deployment/AzureDevOpsPipelineTemplate.java
Labels: bug

#68 Task that allows delete existing subproject
  README.md
  gradle.properties
  src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
  src/main/java/co/com/bancolombia/Constants.java
  src/main/java/co/com/bancolombia/PluginClean.java
  src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
  src/main/java/co/com/bancolombia/task/DeleteModuleTask.java
  src/main/java/co/com/bancolombia/utils/FileAppender.java
  src/main/java/co/com/bancolombia/utils/FileUpdater.java
  src/main/java/co/com/bancolombia/utils/Utils.java
  src/main/resources/structure/root/settings.gradle.mustache
  src/test/java/co/com/bancolombia/factory/ModuleBuilderTest.java
  src/test/java/co/com/bancolombia/task/DeleteModuleTaskTest.java
  src/test/java/co/com/bancolombia/utils/UtilsTest.java
Labels: enhancement

#73 Add new documentation to readme file
  README.md
  src/main/resources/structure/root/readme.md.mustache
Labels: documentation

#76 print help on error task usage
  README.md
  gradle.properties
  src/main/java/co/com/bancolombia/Constants.java
  src/main/java/co/com/bancolombia/task/CleanArchitectureDefaultTask.java
  src/main/java/co/com/bancolombia/task/DeleteModuleTask.java
  src/main/java/co/com/bancolombia/task/GenerateDrivenAdapterTask.java
  src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
  src/main/java/co/com/bancolombia/task/GenerateModelTask.java
  src/main/java/co/com/bancolombia/task/GeneratePipelineTask.java
  src/main/java/co/com/bancolombia/task/GenerateStructureTask.java
  src/main/java/co/com/bancolombia/task/GenerateUseCaseTask.java
  src/test/java/co/com/bancolombia/task/CleanArchitectureDefaultTaskTest.java
Labels: enhancement
