Repository bancolombia/scaffold-clean-architecture, pull requests merged in 2022-03, with the labels that each got.

#194 Refactor and clean plugin
  build.gradle
  examples-ca/example-article/domain/model/src/main/java/co/com/crudtest/model/product/gateways/ProductRepository.java
  examples-ca/example-article/domain/usecase/src/main/java/co/com/crudtest/usecase/crudproducto/CrudProductUseCase.java
  examples-ca/example-article/infrastructure/driven-adapters/jpa-repository/src/main/java/co/com/crudtest/jpa/JpaProductImpl.java
  examples-ca/example-article/infrastructure/driven-adapters/jpa-repository/src/main/java/co/com/crudtest/jpa/config/JpaConfig.java
  examples-ca/example-article/infrastructure/driven-adapters/jpa-repository/src/main/java/co/com/crudtest/jpa/helper/AdapterOperations.java
  examples-ca/example-article/infrastructure/entry-points/api-rest/src/main/java/co/com/crudtest/api/ApiRest.java
  src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
  src/main/java/co/com/bancolombia/Constants.java
  src/main/java/co/com/bancolombia/factory/ModuleBuilder.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterAsyncEventBus.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterJPA.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterKms.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterMQ.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterMongoDB.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterR2dbcPostgreSQL.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRSocketRequester.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRedis.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterRestConsumer.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterS3.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterSecrets.java
  src/main/java/co/com/bancolombia/factory/commons/GenericModule.java
  src/main/java/co/com/bancolombia/factory/commons/ObjectMapperFactory.java
  src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointAsyncEventHandler.java
  src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointGraphql.java
  src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointMQ.java
  src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRSocketResponder.java
  src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvc.java
  src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestMvcServer.java
  src/main/java/co/com/bancolombia/factory/entrypoints/EntryPointRestWebflux.java
  src/main/java/co/com/bancolombia/factory/helpers/ModuleFactoryHelpers.java
  src/main/java/co/com/bancolombia/factory/validations/ReactiveTypeValidation.java
  src/main/java/co/com/bancolombia/task/DeleteModuleTask.java
  src/main/java/co/com/bancolombia/task/GenerateEntryPointTask.java
  src/main/java/co/com/bancolombia/task/ValidateStructureTask.java
  src/main/java/co/com/bancolombia/utils/FileUtils.java
  src/test/java/co/com/bancolombia/task/DeleteModuleTaskTest.java
  src/test/java/co/com/bancolombia/task/GenerateDrivenAdapterTaskTest.java
  src/test/java/co/com/bancolombia/task/GenerateEntryPointTaskTest.java
  src/test/java/co/com/bancolombia/task/GenerateHelperTaskTest.java
  src/test/java/co/com/bancolombia/task/GenerateTestTaskTest.java
  src/test/java/co/com/bancolombia/task/ValidateStructureTaskTest.java
Labels: work-in-progress, Improvement

#222 Add driver adapter bin stash
  src/functionalTest/java/co/com/bancolombia/PluginCleanFunctionalTest.java
  src/main/java/co/com/bancolombia/factory/adapters/DrivenAdapterBinStash.java
  src/main/java/co/com/bancolombia/factory/adapters/ModuleFactoryDrivenAdapter.java
  src/main/java/co/com/bancolombia/task/GenerateDrivenAdapterTask.java
  src/main/resources/driven-adapter/bin-stash/bin-stash-local-cache-config.java.mustache
  src/main/resources/driven-adapter/bin-stash/bin-stash-local-cache-config.kt.mustache
  src/main/resources/driven-adapter/bin-stash/build.gradle.kts.mustache
  src/main/resources/driven-adapter/bin-stash/build.gradle.mustache
  src/main/resources/driven-adapter/bin-stash/definition.json
Labels: enhancement, Improvement

#224 example mongo reactive
  examples-ca/deployment/Dockerfile
  examples-ca/deployment/stack.yml
  examples-ca/example-mongo/.gitignore
  examples-ca/example-mongo/README.md
  examples-ca/example-mongo/applications/app-service/build.gradle
  examples-ca/example-mongo/applications/app-service/src/main/java/co/com/emorae/MainApplication.java
  examples-ca/example-mongo/applications/app-service/src/main/java/co/com/emorae/config/ObjectMapperConfig.java
  examples-ca/example-mongo/applications/app-service/src/main/java/co/com/emorae/config/UseCasesConfig.java
  examples-ca/example-mongo/applications/app-service/src/main/resources/application.yaml
  examples-ca/example-mongo/applications/app-service/src/main/resources/log4j2.properties
  examples-ca/example-mongo/build.gradle
  examples-ca/example-mongo/domain/model/build.gradle
  examples-ca/example-mongo/domain/model/src/main/java/co/com/emorae/model/order/Order.java
  examples-ca/example-mongo/domain/model/src/main/java/co/com/emorae/model/order/OrderStatus.java
  examples-ca/example-mongo/domain/model/src/main/java/co/com/emorae/model/order/Product.java
  examples-ca/example-mongo/domain/model/src/main/java/co/com/emorae/model/order/Topping.java
  examples-ca/example-mongo/domain/model/src/main/java/co/com/emorae/model/order/gateways/OrderRepository.java
  examples-ca/example-mongo/domain/usecase/build.gradle
  examples-ca/example-mongo/domain/usecase/src/main/java/co/com/emorae/usecase/orders/OrdersUseCase.java
  examples-ca/example-mongo/gradle.properties
  examples-ca/example-mongo/gradlew
  examples-ca/example-mongo/gradlew.bat
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/build.gradle
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/MongoDBRepository.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/MongoRepositoryOrderAdapter.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/OrderRepositoryImpl.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/config/MongoConfig.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/config/MongoDBSecret.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/document/OrderDocument.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/document/ProductDocument.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/document/ToppingDocument.java
  examples-ca/example-mongo/infrastructure/driven-adapters/mongo-repository/src/main/java/co/com/emorae/mongo/helper/AdapterOperations.java
  examples-ca/example-mongo/infrastructure/entry-points/reactive-web/build.gradle
  examples-ca/example-mongo/infrastructure/entry-points/reactive-web/src/main/java/co/com/emorae/api/ApiRest.java
  examples-ca/example-mongo/infrastructure/entry-points/reactive-web/src/main/java/co/com/emorae/api/config/SpringFoxConfig.java
  examples-ca/example-mongo/lombok.config
  examples-ca/example-mongo/main.gradle
  examples-ca/example-mongo/settings.gradle
Labels: documentation

#228 add example rest consumer
  examples-ca/example-rest-consumer/rest-consumer-client/.gitignore
  examples-ca/example-rest-consumer/rest-consumer-client/README.md
  examples-ca/example-rest-consumer/rest-consumer-client/applications/app-service/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-client/applications/app-service/src/main/java/co/com/bancolombia/MainApplication.java
  examples-ca/example-rest-consumer/rest-consumer-client/applications/app-service/src/main/java/co/com/bancolombia/config/UseCasesConfig.java
  examples-ca/example-rest-consumer/rest-consumer-client/applications/app-service/src/main/resources/application.yaml
  examples-ca/example-rest-consumer/rest-consumer-client/applications/app-service/src/main/resources/log4j2.properties
  examples-ca/example-rest-consumer/rest-consumer-client/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-client/deployment/Dockerfile
  examples-ca/example-rest-consumer/rest-consumer-client/domain/model/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-client/domain/model/src/main/java/co/com/bancolombia/model/user/User.java
  examples-ca/example-rest-consumer/rest-consumer-client/domain/model/src/main/java/co/com/bancolombia/model/user/gateways/UserRepository.java
  examples-ca/example-rest-consumer/rest-consumer-client/domain/usecase/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-client/domain/usecase/src/main/java/co/com/bancolombia/usecase/consumeservice/ConsumeServiceUseCase.java
  examples-ca/example-rest-consumer/rest-consumer-client/gradle.properties
  examples-ca/example-rest-consumer/rest-consumer-client/gradlew
  examples-ca/example-rest-consumer/rest-consumer-client/gradlew.bat
  examples-ca/example-rest-consumer/rest-consumer-client/infrastructure/driven-adapters/rest-consumer/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-client/infrastructure/driven-adapters/rest-consumer/src/main/java/co/com/bancolombia/consumer/ObjectRequest.java
  examples-ca/example-rest-consumer/rest-consumer-client/infrastructure/driven-adapters/rest-consumer/src/main/java/co/com/bancolombia/consumer/ObjectResponse.java
  examples-ca/example-rest-consumer/rest-consumer-client/infrastructure/driven-adapters/rest-consumer/src/main/java/co/com/bancolombia/consumer/RestConsumer.java
  examples-ca/example-rest-consumer/rest-consumer-client/infrastructure/driven-adapters/rest-consumer/src/main/java/co/com/bancolombia/consumer/config/RestConsumerConfig.java
  examples-ca/example-rest-consumer/rest-consumer-client/infrastructure/entry-points/api-rest/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-client/infrastructure/entry-points/api-rest/src/main/java/co/com/bancolombia/api/ApiRest.java
  examples-ca/example-rest-consumer/rest-consumer-client/lombok.config
  examples-ca/example-rest-consumer/rest-consumer-client/main.gradle
  examples-ca/example-rest-consumer/rest-consumer-client/settings.gradle
  examples-ca/example-rest-consumer/rest-consumer-server/.gitignore
  examples-ca/example-rest-consumer/rest-consumer-server/README.md
  examples-ca/example-rest-consumer/rest-consumer-server/applications/app-service/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-server/applications/app-service/src/main/java/co/com/bancolombia/MainApplication.java
  examples-ca/example-rest-consumer/rest-consumer-server/applications/app-service/src/main/java/co/com/bancolombia/config/UseCasesConfig.java
  examples-ca/example-rest-consumer/rest-consumer-server/applications/app-service/src/main/resources/application.yaml
  examples-ca/example-rest-consumer/rest-consumer-server/applications/app-service/src/main/resources/log4j2.properties
  examples-ca/example-rest-consumer/rest-consumer-server/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-server/deployment/Dockerfile
  examples-ca/example-rest-consumer/rest-consumer-server/domain/model/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-server/domain/model/src/main/java/co/com/bancolombia/model/usuario/Usuario.java
  examples-ca/example-rest-consumer/rest-consumer-server/domain/model/src/main/java/co/com/bancolombia/model/usuario/gateways/UsuarioRepository.java
  examples-ca/example-rest-consumer/rest-consumer-server/domain/usecase/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-server/gradle.properties
  examples-ca/example-rest-consumer/rest-consumer-server/gradlew
  examples-ca/example-rest-consumer/rest-consumer-server/gradlew.bat
  examples-ca/example-rest-consumer/rest-consumer-server/infrastructure/entry-points/api-rest/build.gradle
  examples-ca/example-rest-consumer/rest-consumer-server/infrastructure/entry-points/api-rest/src/main/java/co/com/bancolombia/api/ApiRest.java
  examples-ca/example-rest-consumer/rest-consumer-server/lombok.config
  examples-ca/example-rest-consumer/rest-consumer-server/main.gradle
  examples-ca/example-rest-consumer/rest-consumer-server/settings.gradle
Labels: documentation, enhancement

#227 add example r2dbc
  examples-ca/example-r2dbc/.gitignore
  examples-ca/example-r2dbc/README.md
  examples-ca/example-r2dbc/applications/app-service/build.gradle
  examples-ca/example-r2dbc/applications/app-service/src/main/java/co/com/bancolombia/MainApplication.java
  examples-ca/example-r2dbc/applications/app-service/src/main/java/co/com/bancolombia/config/UseCasesConfig.java
  examples-ca/example-r2dbc/applications/app-service/src/main/resources/application.yaml
  examples-ca/example-r2dbc/applications/app-service/src/main/resources/log4j2.properties
  examples-ca/example-r2dbc/build.gradle
  examples-ca/example-r2dbc/deployment/Dockerfile
  examples-ca/example-r2dbc/deployment/docker-compose.yml
  examples-ca/example-r2dbc/domain/model/build.gradle
  examples-ca/example-r2dbc/domain/model/src/main/java/co/com/bancolombia/model/postmodel/PostModel.java
  examples-ca/example-r2dbc/domain/model/src/main/java/co/com/bancolombia/model/postmodel/gateways/PostModelRepository.java
  examples-ca/example-r2dbc/domain/usecase/build.gradle
  examples-ca/example-r2dbc/domain/usecase/src/main/java/co/com/bancolombia/usecase/post/PostUseCase.java
  examples-ca/example-r2dbc/gradle.properties
  examples-ca/example-r2dbc/gradlew
  examples-ca/example-r2dbc/gradlew.bat
  examples-ca/example-r2dbc/infrastructure/driven-adapters/r2dbc-postgresql/build.gradle
  examples-ca/example-r2dbc/infrastructure/driven-adapters/r2dbc-postgresql/src/main/java/co/com/bancolombia/AdapterImpl.java
  examples-ca/example-r2dbc/infrastructure/driven-adapters/r2dbc-postgresql/src/main/java/co/com/bancolombia/MyReactiveRepository.java
  examples-ca/example-r2dbc/infrastructure/driven-adapters/r2dbc-postgresql/src/main/java/co/com/bancolombia/Post.java
  examples-ca/example-r2dbc/infrastructure/driven-adapters/r2dbc-postgresql/src/main/java/co/com/bancolombia/config/PostgreSQLConnectionPool.java
  examples-ca/example-r2dbc/infrastructure/driven-adapters/r2dbc-postgresql/src/main/java/co/com/bancolombia/config/PostgresqlConnectionProperties.java
  examples-ca/example-r2dbc/infrastructure/entry-points/reactive-web/build.gradle
  examples-ca/example-r2dbc/infrastructure/entry-points/reactive-web/src/main/java/co/com/bancolombia/api/ApiRest.java
  examples-ca/example-r2dbc/lombok.config
  examples-ca/example-r2dbc/main.gradle
  examples-ca/example-r2dbc/settings.gradle
Labels: documentation, enhancement
